### ISSUE TITLE
Using server hosted BlazorAppPackage

### ISSUE THREAD

**Issue by soend** [Daddoon/BlazorMobile#142]
Hello, this is create project and i really like the idea but i was wondering if it would be possible to make the webview to show blazor app package downloaded from a server. That way if i make changes in the blazor app i would not have to push out new apk every time.

**Comment by Daddoon** [comment]
Well this is a very interesting idea. I already though about this scenario, but never added it to the issues list.

In my opinion, you should be able to offer this behavior by modifying your code logic in the **WebApplicationFactory.RegisterAppStreamResolver** given delegate.

If my memory is good, the current delegate implementation is in the AppPackage project, but feel free to register it from somewhere more convenient for you.

The idea to achieve your goal would be:

- Having a "base" version of your app, already shipped in your app for the first launch (or not if you have another idea of mecanism)
- Having a webserver that can deliver an updated BlazorMobile app package.
- The idea is that when you have an update available (fetched from your server) you would only have to download it (the BlazorMobile app package zip) and stock it on the user device, in a private storage area of your app.
- Then when your app load a second time (or if you reload the WebView by yourself), just adjust the RegisterAppStreamResolver code to open the app stream from your downloaded and cached zip, instead of the embedded version. Actually, you may only have to write a code that manage loading the app if there is any other version downloaded or not, and it will work transparently.

The only thing you cannot do with this scenario, is if you need to update the Xamarin.Forms abstraction layer, like adding new interop services and behavior to native.

But if you only updated the Web app (Blazor), there will be no problem at all.

**Comment by Daddoon** [comment]
Btw, i think it would be nice to have a sample / little guide about this type of feature in the README.

I keep this issue open for tracking, as i will try to add some example guide for this request.

**Comment by soend** [comment]
Thanks, you described exactly the idea what i had. Would be nice to get some pointers where to start when one would like to implement this.

**Comment by Daddoon** [comment]
If you are patient, i will try to post a guide during this week.

**Comment by Daddoon** [comment]
Sorry, i had a lot of works.

I still have to write documentation about this, and i think i will take this into the form of a tutorial, here or on my future website.

Stay tuned!

**Comment by Daddoon** [comment]
Working on this functionnality, at least to make this the more straightforward to use.

**Comment by Daddoon** [comment]
This will take a little more time to me, so i will add theses "helpers" for a next release ! Sorry !

**Comment by Daddoon** [comment]
Done, will update the doc for this need when releasing the update today

**Comment by Daddoon** [comment]
@soend The functionnality you asked is now available on the last version of BlazorMobile. 
See the documentation here for more info:

https://github.com/Daddoon/BlazorMobile/#loading-several-or-external-blazormobile-apps

**Comment by soend** [comment]
> @soend The functionnality you asked is now available on the last version of BlazorMobile.
> See the documentation here for more info:
> 
> https://github.com/Daddoon/BlazorMobile/#loading-several-or-external-blazormobile-apps

Crazy times and been busy with other projects but now im back with this. This feature looks really good, i will def try it out in my project! :)

**Comment by Daddoon** [comment]
Thanks for your feedback :D
