### ISSUE TITLE
WASM and Server side throws an exception using XamarinBridge

### ISSUE THREAD

**Issue by rfcdejong** [Daddoon/BlazorMobile#149]
A new project based on the default BlazorMobile template. I have it working on an android and iOS phone simulator. It also works on Electron. Sadly it throws the following exception when using the XamarinBridge. Starting both the client and the server projects.

Server side:

> Content root path: C:\Repos\MyBlazorMobile\MyBlazorMobile.Blazor.Server
> Now listening on: http://127.0.0.1:5080
> Application started. Press Ctrl+C to shut down.
> Detected Blazor implementation: .NET Core (Server-side)
> BlazorMobile was unable to connect to native through websocket server to execute task 253d1956-706c-400c-8725-172acb10bcef
> Initialization success: False
> Device is: Browser
> fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
>       Unhandled exception in circuit 'Uqgwrd8a5xHql9wN5QUwO-SCvgwXE-6JDCzZuqaeT4k'.
> BlazorMobile.InteropException: BlazorMobile was unable to connect to native through websocket server to execute task 2391f12d-a333-4ce7-941b-8ce8ef6bc8b2
>    at BlazorMobile.Common.Models.TaskDispatch.ThrowExceptionIfFaulted()
>    at BlazorMobile.Common.Services.MethodDispatcher.<>c__DisplayClass2_0`1.<CreateTaskDispatcher>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location where exception was thrown ---
>    at MyBlazorMobile.Blazor.Pages.BlazorMobilePage.ShowPlatform() in C:\Repos\MyBlazorMobile\MyBlazorMobile.Blazor\Pages\BlazorMobilePage.razor:line 16
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
>    at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
>    at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<.cctor>b__23_0(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)

I'm not sure if I'm doing something wrong, perhaps I should do something with 192.168.1.118:8888 ?

**Comment by Daddoon** [comment]
There is a missing information in your question.

Does this exception occur when using on the Device (that used it's own local adress) or when you are testing WASM or Server-side from a browser with remote debugging ?

If this is the latest, double check if it's an error of my side on the template but the Blazor project must use the same port as the one defined on your Xamarin.Forms project, and for the IP adress the Blazor app must connect for debugging, it must match the IP adress of the targeted device. I don't remember if this is clear enough in the doc.

On UWP it should be 127.0.0.1 with NetworkIsolation disabled, as stated in the doc. For iOS and Android as targeted device, you must find the IP of your device on your local network.

**Comment by rfcdejong** [comment]
Just on my local device, a windows 10 laptop in Visual Studio 2019 (with 3.1 preview3)
I did not modify any code generated from the template. (beside testing with ip and slashing away)

Startup projects MyBlazorMobile.Blazor and MyBlazorMobile.Server 

Using default port (8888) as I did not modify anything.
I tried 127.0.0.1 and my local IP on several places.. I just have no clue in how to not get the exception, as you see I did receive 1 time in Console.Writeline("Device is: Browser") but that exception keeps throwing. I even get the exception with slashing away EnableClientToDeviceRemoteDebugging.

**Comment by Daddoon** [comment]
If you are testing from your Windows 10, enabling **EnableClientToDeviceRemoteDebugging** is mandatory (and i also advise to only call it when in Debug mode), so you must keep it, otherwise you will not be able to remote test anything.

If you are sure that your are listening to the right IP and the right port:

- Is the Native app launched (In Debug configuration with or without Debugging) before you launch your Windows debug ?
- Do you have any firewall on ?

I think you are missing the startup projects otherwise: Native should be "MyBlazorMobile.YourTargetPlatform" and Blazor project "MyBlazorMobile.Blazor.Server" OR "MyBlazorMobile.Blazor". 

So if you intent was to Debug your Blazor app from a Android or iOS app, you should launch **MyBlazorMobile.Android** first (or at the same time), and then **MyBlazorMobile.Blazor**. The Android target contain the **MyBlazorMobile** project, wich contain the implementation of the webserver executed for feeding the app.

Actually "MyBlazorMobile.Blazor.Server** is named like this because it's the "Server-side" version of Blazor running on it, based on your WASM project, in order to add breakpoints to test your code, but it is not the native host of your remote device.

Is it more clear ?

EDIT: So if you want to Debug your Blazor app with Breakpoint, startup projects must be **MyBlazorMobile.Blazor.Server** and **MyBlazorMobile.Android** (for instance).

**Comment by rfcdejong** [comment]
It works on Android, Desktop and UWP. Just not on Browser only. Debugging works fine (I like it better than alt+shift+d in browser) 

If I only startup MyBlazorMobile.Blazor then it shows throws the same exception in the Browser Console. Does it always have to connect to a Platform? (UWP, Desktop, Android or iOS). Just wanted to test browser only on local machine (expecting it to behave like a PWA)

Which project is the Native one compared to a ServiceWorker in browser (PWA) ?

**Comment by Daddoon** [comment]
Yes, you must have a native app backend behind, this is main goal of BlazorMobile, being able to use a Blazor app as an hybrid app with access to native functionnalities through Xamarin.

You cannot use BlazorMobile functionnalities with just the Blazor alone: Of course the XamarinBridge you were seeing in error is actually a native implemented service you may call on your device, so it's normal it fail to connect if you just launch your app alone.

But anyway, nothing prevent you to Design the code of your Blazor app to work as a PWA app in some specific case if you need, it's just about how you implement your Dependency Services injection at startup and how you instanciate your app too.

If you want to avoid the BlazorMobile logic and behaviors at startup, you just have to edit the **MobileApp** component of your project, in the Blazor project. This way, you may conditionnaly load or not load the BlazorMobileComponent at startup. Also alternatively, you could use another regular Blazor project that just don't launch the same base component, but use the same Page / Views...There is many way to achieve what you need.

With this is in mind, you then just have to configure your template with the PWA bits for service worker, but this is outside the scope of BlazorMobile actually, as i don't have written any docs on that, but you should find this on the internet.

But to be clear, with Blazor and BlazorMobile, you can both architecture your app for the web and web with PWA and for mobile / embedded solutions too, as the Blazor side will always be a regular Blazor app.

As i said, native project is **MyBlazorMobile** project (the shortest one), even if it's a class library for your platform specific project, it contain the shared native code. At a lower level, you should see on the platform specific projects, but the core of native things that are executed through this project.

There is no service worker on the default template of BlazorMobile (i mean i didn't test), but i a said earlier, you can do this modifications about this as nothing prevent you to do it.

Also, keep in mind, if my memory is correct, that cache/cookies and indexDB are cleared at each startup on native mobile devices (iOS, Android, UWP), and i don't think i made this configurable at the moment. Of course this only concern native mobile devices, you are not impacted if it's only a Blazor app in any regular Browser.

**Comment by rfcdejong** [comment]
I like your solution to embed the blazor app in a browser and allow native communication. So the exception is expected cause there is no native side / PWA to show the message "Device is: Browser". 

I have no clue if the cache/cookie and indexDB clearing will be an issue, but for now I just explored your solution to be able to deploy cross platform and on mobile quickly without creating seperate xamarin projects duplicating a blazor frontend.

Requirements might be that a mobile app looks completely different and has other functionality, in that case it is still good for UWP and Desktop (though I don't currently favor Electron.NET because of electronize logo, menu, etc..)

I will close this issue as it is by design (unless you want to document it a bit clearer, you can reopen it)

**Comment by Daddoon** [comment]
You are right, maybe the error message should be more explicit. Actually, initially the behavior was to return "Unknown", but this is something i didn't fix.

For indexDB and other things, i was expecting that end user may use native storage with BlazorMobile (with Entity Framework Core or other), so this was not a priority / blocking.

Initially it was because i was expecting some "random" crash to be issued from cache. Actually it's just that UWP in VS2019 in some debugging condition was instable.

If it's blocking however, it may be easy to allow or disallow this behavior programmatically at startup.

Yes, you can add any "extra" functionnality on each project, as you have access to Xamarin and Xamarin.Forms. For Electron you will have to do thing with Electron/ElectronNET API of course.

But you know actually what you see with Electron is just the default shipped template of Electron. Correct me if i'm wrong, but the logo / menu etc. can surely be hidden / added / removed programatically with the Electron API.
