### ISSUE TITLE
Create Android app from server-side Blazor app

### ISSUE THREAD

**Issue by OmiCron07** [Daddoon/BlazorMobile#151]
I already have my Blazor server-side app created with Electron.Net. It's working good as a Windows application. Now, I would like to package it as an Android app. Is it possible with BlazorMobile and how can I achieve it with my existing app?

**Comment by Daddoon** [comment]
The default BlazorMobile template should be already for packaging both.

Actually the main difference with a regular Electron.NET with Blazor and the one is BlazorMobile is that the BlazorMobile implementation don't reference Electron.NET API directly from the Blazor project, instead it use a dependency injection service for interoping with your specific API, in order to keep your Blazor project not linked with any platform specific library.

See [Communication between Blazor and Native](https://github.com/Daddoon/BlazorMobile#communication-between-blazor--native) section, and try to update your code to follow this pattern on your Blazor Electron.NET Project.

In my opinion just start from the BlazorMobile template and follow the README.
If you have any platform specific call to do on Android (like for storage, SQLite or else), you will have to implement them on your projects with the Xamarin Dependency service, in order to call them from the class libraru Xamarin project.

Actually it would be too long for me to explain everything here. Read the manual first, to see how it works, and then i suggest you to create a BlazorMobile solution project, and then use a diff tool, like WinMerge, or anything else, or inspecting yourself manually how Startup.cs, and the additionnal services, are registered, named etc.

Actually BlazorMobile support ElectronNET too so maybe the it will be easier to you to inspect the ElectronNET template for BlazorMobile.

**Comment by OmiCron07** [comment]
Alright, thank you!

**Comment by Daddoon** [comment]
Don't hesitate to ask me detailled questions here if you have an issue to make this working.
