### ISSUE TITLE
BlazorMobile rocks for LOB apps. Looking for best dev & testing start-up project

### ISSUE THREAD

**Issue by JordanRavka** [Daddoon/BlazorMobile#161]
**Your BlazorMobile project is amazing!**

- Everything "just works" like magic to create offline apps (with Sqlite, etc..) on EVERY platform   (no Sega Dreamcast support?!)
- PLEASE keep going!!   (not sure why more devs don't know about this)

**Questions & notes...** 

- Need **fastest way to build & modify code**
- I tested every project type and here are the results:

**Note: Added "Echo" for 2-way testing**

`public async Task<string> Echo(string s) { return s; } 
IXamarinBridge { Task<string> Echo(string s); } // on interface
echoResponse = await XamarinBridge.Echo("Echo from .Blazor"); } // on screen`

### .Desktop (electron)
Pros

- Cross communications works
- "DisplayAlert" does not launch anything BUT "Echo" returned resultConsole 
- Logging works

Cons

- Very slow startup
- Does not hit breakpoints on XamarinBridge
- No Chrome Dev Tools

### .UWP
**Pros**
- Very fast startup
- Breakpoints hit

**Cons**
- No Chrome Dev Tools
- Blazor to Server needs 2 clicks to work (maybe bug)
- - one click needed to hit breakpoint
- - two clicks needed to actually change the GUI

### .Server (web)
**Pros**
- Super-Fast startup
- Chrome Dev Tools

**Cons**
- Blazor-to App-doesn't seem to work
- WebSocket connection to 'ws://127.0.0.1:5080/contextBridge' failed: Error during WebSocket handshake: Unexpected response code: 200  BlazorMobile: Socket error: { "isTrusted": true }

### Server is my preference if bridge connection can be fixed
- probably me, I'm not "techy" :)

This is productivity heaven for every LOB offline developer! Thank you!!!

**Comment by JordanRavka** [comment]
On UWP, 

As mentioned, on the "BlazorMobile" page, the Echo(string s) call to XamarinBridge does not return a result the first click but cool afterwards.  Interestingly, if I leave and come back to the page, the error happens again but also again, just once then good. 

UWP is fast enough to develop with. With chrome tools and this click-twice error solved, just about perfect!

**Comment by Daddoon** [comment]
Hi @JordanRavka !

Thanks for your messages !
I was very busy today, so i will take a look to your questions and answers tomorrow !

Regards

**Comment by JordanRavka** [comment]
I just can't believe the work you put into this! I build very large lob systems (100's of app pages, cloud architecture, etc..) and am migrating away from SPA (Knockout) & c# back-end. 

With your system, I have a whole new resume :)

**Comment by Daddoon** [comment]
> **Your BlazorMobile project is amazing!**
>

Thanks a lot ! I put a lot of passion while developping this ecosystem.
 
>     * Everything "just works" like magic to create offline apps (with Sqlite, etc..) on EVERY platform   (no Sega Dreamcast support?!)

This was one of the main goal, as i think nowadays, app developpement should focusing on something like "write once, run everywhere". I know that some people may not agree with that, but i think this is more true than before when dealing with Web technologies, as the web is for me the Universal UI/UX ecosystem.

Having strong typed langages like C# (or i imagine any .NET CLR) in the web browser, for developping your Business logic is the "Cherry on the cake", and being able to discuss with the native side in the same language is like a "second cherry" !

So also, thanks to Xamarin/Mono team and Microsoft for all their respective work !

Keep in mind that every platform that can deal with WebAssembly in the Web browser should be able to use BlazorMobile or Blazor only as PWA (not a scenario i have yet managed specifically, but this is not something blocking !).

That's also why the Android BlazorMobile packages does embed a GeckoView engine. This is in order to have the same browser and WebAssembly support on all Android versions, from 4.4 to latest.

> 
>     * PLEASE keep going!!   (not sure why more devs don't know about this)
> 

I think it's also because i'm not advertising this project globally, i'm not fond about bragging "what i know" "what i do", i prefer to dedicate my time on what is essential in life, and being popular is not a priority at all.

Oddly, Blazor Desktop support with ElectronNET has been advertised through some Microsoft videos, and also Blazor Native Bindings support (a Blazor developement style with Xamarin.Forms), but this project not specifically. But i suppose that Microsoft is more interested in promoting their own products first, and this is fair, even if this project is derivated from their own products (Blazor and Xamarin).

I keep going, but i slowed down a little, as i'm less working lately, and also because the core functionnalities of BlazorMobile are present in my opinion.

But feel free to advertise or doing some video about BlazorMobile if you like it a lot, i would be very happy !

> 
> **Questions & notes...** 
> 
>     * Need **fastest way to build & modify code**
> 

How are you testing your projects when building / testing ?
Because of course you can just click on "Debug" and launch the full app build / deploy, but the fastest way in the long run in my opinion, is to:

- Launch your "Native" project side-loaded **without** debugger, but with Debug functionnalities enabled in code in order to allow external communication
- Launch your "Server" project **WITH** debugger and configure it to connect to your Native device at boot.

This way, you only launch and debug the Blazor **server-side** version from your computer web browser, and you can access breakpoints from Visual Studio. Any interactions to native will be transfered to your Device if you configured the remote debugging correctly.

So the debugging and test experience is very fast in my opinion.

The main downside of all that is:

- The server-side version as some differents behavior than WASM version when debugging, as it has some issue when crashing when doing JSInterop, but this issue is not related directly to BlazorMobile. But note that you can also use the Blazor WASM version to connect to your native device when debugging from your web browser, you will only be limited on the Debugging features offered by Microsoft (but you may take a look at this, things may have improved on Microsoft side).

- If your native app is opened and your debugging web browser tab, when doing some test, in some case you may receive some events twice (or having some weird behavior of this nature) because the Websocket server running on your mobile native device may receive events from two different source (localhost and your remote dev computer), and will then answer to all connected clients instead of the client origin, as i don't have set any filter for this kind of technical scenario.

But normally this should only happen while having a debugging experience remotely, feel free to send me a repro project if you think you are having another issue not related to this, if you think this is a bug.

>     * I tested every project type and here are the results:
> 
> 
> **Note: Added "Echo" for 2-way testing**
> 
> `public async Task<string> Echo(string s) { return s; } IXamarinBridge { Task<string> Echo(string s); } // on interface echoResponse = await XamarinBridge.Echo("Echo from .Blazor"); } // on screen`

If you have any doubt about anything with the API, you may try to fork the BlazorMobile source code and launch the "InteropApp" projects in source code.

Theses projects are like the "Playground" project for me in order to test that API calls are working, and if i have to write specific page for test and workarounding issues on specifics platforms.

In my opinion, it would be clever to add some of the **InteropApp** project tests/examples to the **BlazorMobile.Templates**, but i don't have yet taken the time to schedule this nor writing a GitHub issue in order to to this.

> ### .Desktop (electron)
> 
> Pros
> 
>     * Cross communications works
> 
>     * "DisplayAlert" does not launch anything BUT "Echo" returned resultConsole

On wich version of BlazorMobile did you have this issue on **DisplayAlert** ?
The latest version is using ElectronNET 7.x and the previous one ElectronNET 5.x.

I have managed to write a "fake" (meaning not fully compliant / finished) Xamarin.Forms API for ElectronNET, and DisplayAlert was one of the basic things i have managed to deal with.

So if it's not working to day, it would be interesting to know if you have it from scratch from templates, and if so, wich version of BlazorMobile / Electron ?

Otherwise, it was intended to work.

> 
>     * Logging works
> 
> 
> Cons
> 
>     * Very slow startup

Yes, but this behavior is related to the current ElectronNET API way to deploy app. I don't have control on this.

> 
>     * Does not hit breakpoints on XamarinBridge

I don't have written doc about this issue (sorry for that) but you **CAN** hit breakpoints on XamarinBridge with ElectronNET.

The only difference, because of the way ElectronNET is launching, is that you have to **Attach debugger** to the ElectronNET created process for your app.

This mean that when your app is fully launched with ElectronNET, you will have to attach to the right process, the debugger. On my computer, if my memory is right, it should be CTRL+ALT+P, or just go to the Debug -> Attach to Process menu.

Then everything should be debuggable.

> 
>     * No Chrome Dev Tools

On ElectronNET, you should be able to open them in the last menu. There is something like "Open Developer Tools".

> 
> 
> ### .UWP
> 
> **Pros**
> 
>     * Very fast startup

This is my preference for Debugging experience !

> 
>     * Breakpoints hit
> 
> 
> **Cons**
> 
>     * No Chrome Dev Tools
> 
>     * Blazor to Server needs 2 clicks to work (maybe bug)
> 
>     * * one click needed to hit breakpoint
> 
>     * * two clicks needed to actually change the GUI
> 

I don't have this behavior, can you send me a repro project ?
Otherwise, you can't have Dev Tools on it. Also UWP Web Browser debugging feature is lacking on VS2019, thanks to Microsoft to have removed some support on that.

If you launch the Debugging on UWP with VS2017 instead (beware: Blazor project cannot build by itself on VS2017), you will be able to access some of the UWP Browser debugging experience, many being able to open the Javascript and Console windows from the UWP Browser, in Visual Studio. Keep in mind that UWP may crash in Debug with VS2017 at startup...I can't do anything about that if it occur.

That's why in my opinion, the best way to have fast development and Chrome Dev Tools while debugging, is to use Remote debugging with your Computer, as i have mentionned. With UWP you will have to disable Network isolation to do that also.

See [Device remote debugging & Debugging from NET Core 3.0](https://github.com/Daddoon/BlazorMobile#device-remote-debugging--debugging-from-net-core-30) .

In this same doc, this specifically for UWP:

> Additional configuration for UWP
>
> On UWP, because of the NetworkIsolation behavior, you cannot connect by default from your PC to the UWP app.
>
> You must execute this command in background during development in order to allow incoming remote connection, and so remote debugging, in your UWP app:
> 
> CheckNetIsolation loopbackexempt -is -n=YourUWPPackageFamilyName

> Of course, replace YourUWPPackageFamilyName by your package name on UWP. You can find it in the Packages tab of your Package.appxmanifest, at the end.

See also these notes about UWP:

- [My Xamarin services are not found when interoping in UWP](https://github.com/Daddoon/BlazorMobile#my-xamarin-services-are-not-found-when-interoping-in-uwp)
- [Cannot connect to a remote webserver on UWP](https://github.com/Daddoon/BlazorMobile#cannot-connect-to-a-remote-webserver-on-uwp)
- [Unable to connect to UWP remotely even with NetworkIsolation disabled](https://github.com/Daddoon/BlazorMobile#unable-to-connect-to-uwp-remotely-even-with-networkisolation-disabled)

> 
> ### .Server (web)
> 
> **Pros**
> 
>     * Super-Fast startup
> 
>     * Chrome Dev Tools
> 
> 
> **Cons**
> 
>     * Blazor-to App-doesn't seem to work
> 
>     * WebSocket connection to 'ws://127.0.0.1:5080/contextBridge' failed: Error during WebSocket handshake: Unexpected response code: 200  BlazorMobile: Socket error: { "isTrusted": true }
> 
> 
> ### Server is my preference if bridge connection can be fixed
> 
>     * probably me, I'm not "techy" :)
> 

As you said, this scenario is the best for fast iteration on Native app, with Blazor C# debug support during debug session.

- Is Remote debugging enabled on your Native project ?
- Is the port the same on your Blazor Server / Blazor WASM project and your Native project ?
- Is the IP Address written in your Blazor Server / Blazor WASM project pointing to your native app embedding your Blazor app ?

At the moment, IP Address for remote debugging is hardcoded at build time (not using a configuration file), so you have to manage to get your device IP on your network, and set it in the Blazor Web project in **BlazorMobileService.EnableClientToDeviceRemoteDebugging()** (you may have to set that on the .Blazor.Server and .Blazor project depending if you want to test them both with remote debugging), same for the port that should be the set the same, see in your shared Xamarin project (the project with the shortest name):

```csharp
#if DEBUG
            WebApplicationFactory.EnableDebugFeatures();
#endif
            WebApplicationFactory.SetHttpPort(8888);
```

But take a look at the BlazorMobile documentation, i'm pretty sure that some if your issues are covered in it.

> 
> This is productivity heaven for every LOB offline developer! Thank you!!!

Thanks again ! I'm pretty happy about this.
Feel free to contribute, comment, or add any questions.

Regards,
Guillaume

**Comment by Daddoon** [comment]
> 
> 
> I just can't believe the work you put into this! I build very large lob systems (100's of app pages, cloud architecture, etc..) and am migrating away from SPA (Knockout) & c# back-end.
> 
> With your system, I have a whole new resume :)

I'm very pleased about that !

If you have any public projects (not specifically open-sourced) that you wish to migrate to Blazor & BlazorMobile in order to support Mobile and Desktop, feel free to share them with me, as it would be also a good advertising for this project too, as i can't yet disclose the project i'm working on with a Client.

**Comment by Daddoon** [comment]
Juste an additionnal note, if you only want to support Blazor with Desktop (ElectronNET), BlazorMobile is not mandatory, as this is possible to launch Blazor in server-side mode with ElectronNET with very few things to configure.

You would be able to also communicate with "Native" as you would be able to reference Native and Blazor project together in the same assembly, so some things are faster to write and do, i mean, initially.

This is just a note. If you need to have to manage the same app working on different systems, ElectronNET (Desktop) & iOS, Android, UWP (Mobile), then i advise you to use the BlazorMobile interaction model, as you will not be limited to Desktop.

**Comment by JordanRavka** [comment]
I am so sorry. 

I have "Chronic Fatigue Syndrome" which means if lucky, my brain works 20 minutes a day. This helps explain my relentless devotion to productivity and my excitement surrounding your work. 

Please give me a day or 2 to properly answer your questions with the respect deserved. I will post bits & pieces asap.

**Comment by Daddoon** [comment]
No problem, take your time !

**Comment by JordanRavka** [comment]
My apologies. This is the first time my brain can respond, Still don't know why I am constantly fired :)

Few things:

**1. Please consider changing your name**
Your not just mobile, your "BlazorOnEverything". Plus looks like google / MS took over "BlazorMobile".. again, weird they don't know about you.

 **2. Your 100% right about testing.** 
Please ignore everything I mentioned. I am actually going to connect UI / App using a WebSocket. This disconnect is a bit of a pain but ensures every scenario works (including web)... plus, I am not techie and I get it :)

There is so much more I want to say but my brain shut's down in 20 min and need to code :)

I am proceeding ahead knowing your blazor-on-everything solution will get me to the finish line and forever grateful!

**Comment by Daddoon** [comment]
1. I'm still the fourth result on Google for "Blazor Mobile". I think BlazorMobile is still a good name, as the chances that people are looking for Blazor + Mobile in search are higher than something else.

In my opinion, the Microsoft press is putting some ambiguities on what they are releasing, as Blazor in developer mind is more about "Web + C# + Razor" rather than something else. I understand that when they say "we are releasing Blazor on mobile" they are just talking about the Blazor programming metamodel / annotations.

I still think their work is excellent, but we are just swimming in some technical ambiguities in the press.

However the current official Microsoft repo is not ambiguous, as the name is **MobileBlazorBindings**.

And in my opinion, their project is great, as they are integrating their own bricks into the Xamarin engine, this mean you could use Blazor (Native) and Blazor (HTML) both in the same app ! Of course, not mixed together, but this could work hand in hand.

They actually know about this project, at least some people, as i discussed with Daniel Roth some month ago (https://github.com/danroth27) , from Microsoft, and he is a very cool guy !

I think they are taking the right direction, Mobile Blazor Bindings is more about creating a new programming model on the Native side, so it's something new. Same, i have read from Steve Sanderson on the web that they are thinking about creating their own Desktop Web renderer "brick" instead of using an heavy ElectronNET app for Blazor.

But at the same time, BlazorMobile is here for fast iteration and bootstrapping new projects. I think it's a very good thing for a consistant UI or if you want to startup / bootstrap your own business very fast. It leave the choice to migrate to something else in the future, but starting with something from day 1 on Web + Mobile + Desktop.

The result is end to yourself then.

2. If you have any issues, please tell me. As i said before, for fast developement pace, generally i test and debug everything in Chrome or Firefox directly, just keeping the good IP/Port settings on a background app (i'm using UWP personnally, so set to 127.0.0.1 with NetworkIsolation disabled).

This way i can launch debug sessions rapidly, and only have to stop and restart the UWP app only if i have written new code on the native side. The Blazor side can be redeployed at any moment without any Native rebuild / restart as they are two distinct projects when executed. And as said before, i'm using the .Server project, in order to set breakpoint and inspect while debugging.

Happy coding !

**Comment by JordanRavka** [comment]
I am so sorry I haven't gotten back, CFS is a bitch :) 

But once again, thank you for doing all this great work and getting back to the community. I still think you should call it "BlazorThatWorksOn*****Everything", but it's your labor of love to name and fly :)

Good luck to you, and when my brain works and can code, I will be back!
