### ISSUE TITLE
Several blazor apps in one mobile app

### ISSUE THREAD

**Issue by nightBaker** [Daddoon/BlazorMobile#163]
Is it possible unite two or more blazor apps in one mobile application ?

**Comment by Daddoon** [comment]
Hi !

Theorically, yes you can but this depend on multiple factor.

Nothing prevent you to ship multiple (or download) multiple Blazor app package in your native app, redirect the "application stream resolver" in the API, and reload the WebView.

However it is true that maybe not all scenario are suitable.
With your question i see theses type of scenario:

- Being able to switch from one Blazor package / app,  to another one
- Being able to allow update of the Blazor app without having to update the app on the stores, by downloading the update and side-loading it.
- Being able to load multiple Blazor app at the same time (even if one is in the background), and being able to close one app, and then resume the previous one if needed.

The two first entries are possible in my opinion, but you may have to play with your **BlazorWebView** object, and the **WebApplicationFactory.AppStreamResolver** in order to achieve by yourself this behavior. Note that theses two kind of scenario will likely be covered by https://github.com/Daddoon/BlazorMobile/issues/142 and https://github.com/Daddoon/BlazorMobile/issues/144 .

I have started some work on this but didn't have the time to finish at the moment, as i'm working on it in my free time, and i have still some work to finish to a client. The branch for this work is here https://github.com/Daddoon/BlazorMobile/tree/dev_blazormobile_3.2.0-preview1.20073.1_sideload_package but still have to be finished, same for the documentation, and also i have to update/merge it with the codebase of the master branch.

For the third scenario written, i'm not sure it would be working out of the box. I have made some work in order to allow theses kind of transitives feature in the future, but i'm pretty sure there is some side effect on the WebView objects (specifically on Android, i imagine), and the current API is lacking from having a way to load / select multiple package at the same time.

However, you may hack this behavior by yourself i think. The idea would be to ship multiple Blazor packages in the same zip file, differenciated by subfolders. However you would have to take the base URI pointing to your apps, and redirect the WebView URI by yourself on the BlazorWebView object.

I cannot guarantee that there is no side effect in some rare cases.

The best would be to develop, update and expose an API for this.

What is your need ?

**Comment by nightBaker** [comment]
My need is the first scenario:
**Being able to switch from one Blazor package / app, to another one**

I am researching for technologies, that allow to develop once with blazor and ship to different platforms. However, we have several web applications and want to combine them in one mobile application.

**Comment by Daddoon** [comment]
Thanks for your feedback.
I will take theses informations in consideration while working on the "side-load" task i'm working on.

As i said, you should be able to do what you want with the tips i given in the previous post, but for an easy API-ready solution, you may have to wait that i implement officially this feature in the API. I'm working on it.

**Comment by Daddoon** [comment]
This functionnality is now available from:

- https://github.com/Daddoon/BlazorMobile/tree/dev_blazormobile_3.2.0-preview1.20073.1_sideload_package

or

- https://github.com/Daddoon/BlazorMobile/tree/dev_blazormobile_3.2.1-preview1.20073.1

For the current supported scenario, you will have to call in your shared Xamarin project:

```csharp
WebApplicationFactory.LoadPackageFromAssembly(packageAssembly, packagePath);
```
This mean that your application package must be shipped within an assembly resource at build time. Dynamic packages side-loaded from an external source is still work in progress.

**NOTE:** ElectronNET support for theses API is still work in progress (so not supported) too, as it assume that i have to implement a fallback to a WASM implementation on ElectronNET in order to switch packages at runtime. It will come very soon.

As i don't have yet shipped documentation or else, you may take a look at the **BlazorMobile.InteropApp** projects in the test folder of the source code. If you go to the Counter page of the app, you will find a button to "switch" to another test app. Please take a look in the public service of this test project to see how this is managed.

This has been tested working on:

- UWP
- Android
- iOS
