### ISSUE TITLE
Console.WriteLine() not working

### ISSUE THREAD

**Issue by xdarkfirestorm** [Daddoon/BlazorMobile#167]
Hi,
when debugging the BlazorMobile project with console any Console.WriteLine calls are not printed in the console. 

I don't know if this is by design, at the moment i'm using jsinterop with console.log to print debug stuff inside the web browsers console instead of the console running aspnetcore.

**Comment by xdarkfirestorm** [comment]
It's working when running the Blazor Server project so probably this is not possible in the client project i guess. Am I right?

**Comment by Daddoon** [comment]
On wich platform are you testing your Console.WriteLine, and where were you expecting the output ? (Native or Web ?).

You may encounter some difference between platforms because of their way of working, and what is running under the hood.

Generally speaking:

- Using .Server project will work with Console.WriteLine because Blazor and Native are in fact running inside a .NET Core app, sharing same memory.
- Using Blazor WASM, it depend where you are using your Console.WriteLine. If made from the Blazor app side, it will be written in the browser logs (visible or not directly visible depending your executing browser). From the Native side, it will works but all values will be written on the Visual Studio debug console ! Also note that UWP will not write it, except if you use Debug.WriteLine instead.

Thats why i'm using this little helper present in the BlazorMobile library (but not exposed):

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text;

[assembly: InternalsVisibleTo("BlazorMobile.UWP")]
[assembly: InternalsVisibleTo("BlazorMobile.Android")]
[assembly: InternalsVisibleTo("BlazorMobile.iOS")]
[assembly: InternalsVisibleTo("BlazorMobile")]
namespace BlazorMobile.Common.Helpers
{
    internal static class ConsoleHelper
    {
        public static void WriteLine(string message)
        {
            message = $"INFO: {message}";

            switch (BlazorDevice.RuntimePlatform)
            {
                case BlazorDevice.UWP:
                    Debug.WriteLine(message);
                    break;
                default:
                    Console.WriteLine(message);
                    break;
            }
        }

        public static void WriteError(string message)
        {
            message = $"ERROR: {message}";

            switch (BlazorDevice.RuntimePlatform)
            {
                case BlazorDevice.UWP:
                    Debug.WriteLine(message);
                    break;
                default:
                    Console.WriteLine(message);
                    break;
            }
        }

        public static void WriteException(Exception ex)
        {
            if (ex == null)
            {
                return;
            }

            WriteError(ex.Message);
        }
    }
}
```

Generally speaking, if you have any logs issue or ambiguity, i suggest you to redirect your messages to the native side (or web if you prefer...depend of what you are more used to) with an interop service, while you are debugging.

**Comment by xdarkfirestorm** [comment]
Thank you. This answered my question and fixes the issue.
