### ISSUE TITLE
[Bug] Select field doesn't pop up list.

### ISSUE THREAD

**Issue by arivera12** [Daddoon/BlazorMobile#187]

**Comment by Daddoon** [comment]
Android ?

**Comment by arivera12** [comment]
Yes. Haven't tested on ios or wp.

**Comment by Daddoon** [comment]
Not cool, but i think some delegates must be worked on with GeckoView.

Android implementation does not use Chrome but GeckoView engine instead, in order to be able to ship a consistent browser from very old versions of Android to nowaday. Same, it allow to use WebAssembly on very old Android OS's too.

The downside of GeckoView is that the app have to implement the expected behavior on the browser executing the app, as GeckoView goal is to allow to develop your own Browser app on Android.

Actually i think the **PromptDelegate** code is missing from current GeckoView implementation. I have started to work on it for this issue: https://github.com/Daddoon/BlazorMobile/issues/183

But i think some code must be done in order to show the select list too (same for date maybe).
Default Firefox Focus implementation in Java look like this: https://github.com/mozilla-mobile/focus-android/blob/f5b22ff78fca22765b8b873b4f70693943ae559a/app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java

This must be added for the next release too, like the file input i think.

I don't have any workaround yet, this must be ported by myself (or anyone willing to) on the PromptDelegate of the Session object of GeckoView.

**Comment by arivera12** [comment]
I see. I will still doing test to see what works and what doesn't work regarding on what I have found at this moment and the list on issue #183 . I will keep providing feedback and bugs reports if any.

**Comment by Daddoon** [comment]
Thanks for the report.

**Comment by Daddoon** [comment]
Select box with simple or multiple is finished on this branch: https://github.com/Daddoon/BlazorMobile/tree/dev_blazormobile_3.2.4-preview2.20160.5_geckoview_fileinput

Still need to port other PromptDelegate code for DateTime and else.

**Comment by arivera12** [comment]
@Daddoon most web developers use custom datetime instead of default browser datetime. Browser datetime field lacks of features than any datetime picker on the web so it's no so important at the moment in my opinion but of course needs to be implemented at sometime. But the select field is very used often. What have been replacing the select field is the autocomplete field but autocomplete field is a custom field not from html standard. I think when ever you can take out a new version including these change it would be awesome. DateTime can wait for a little bit later. The file input implementation per mobile platform is critical this really needs to be implemented.

**Comment by Daddoon** [comment]
Done in BlazorMobile 3.2.4

**Comment by arivera12** [comment]
I just confirmed this is working properly now! Keep up the good work!
