### ISSUE TITLE
Android Application .aab file upload and then download app crashes

### ISSUE THREAD

**Issue by ghost** [Daddoon/BlazorMobile#232]
When I create a .aab file of my blazer android app with API level 28 then it works on Android 4 to Android version 11 but in that case play store not supporting uploading. It gives me an error to upload at least API Level 29. In that case, when I am creating a build on API level 29 it crashes on the app after the splash screen how can I upload the build on API level 28.
But API level 29 build is working on lower version till android 9 how can I upload API level 28 build which is working on every android version.

**Comment by Daddoon** [comment]
The main issue here is that there is a big change on API Level 29 that make GeckoView Engine on Android to crash.

The "fix" on my side would be to update the GeckoView version to a more recent & patched one. The drawback is that i have to reconstruct the Java Bindings for the newer version and it can make some time, time i don't have actually, on this project: https://github.com/Daddoon/Xamarin.Android.GeckoView .

Actually the GeckoView engine was used in order to have consistent WebAssembly support on all Android versions (so very old versions !), but it's a lot less relevant on recent Android devices, as Google Chrome WebAssembly support should be here out of the box.

I had this dicussion by mail with someone some month ago, that you have 2 choices to workaround that in the meantime:

- Detect when you are on a API Level 29 OS/Device , and load the page through a regular Chrome WebView instead of the one shipped through IBlazorWebView (Using GeckoView on Android). The only drawback is that you may have to dig some things by yourself if you find some behavior missings by doing that. I don't have the time yet for writing the code to give the actual fallback.
- Other solution, you may take a try on Mobile Blazor Bindings "Hybrid rendering". I have no clue how mature the thing is nowaday, but it maybe another solution: https://docs.microsoft.com/en-us/mobile-blazor-bindings/walkthroughs/hybrid-hello-world

**Comment by wasimalam072** [comment]
Hi @Daddoon

**Comment by ghost** [comment]
Hi @Daddoon 

we are trying now by using Microsoft.MobileBlazorBindings.WebView.Android but we are facing some problems like Microsoft.aspnetcore.components.webassessmnly 3.2.0 or blazored.localstorage 3.0.0 is not compatible with standard 2.0.

can you please help us with how to proceed with Microsoft.MobileBlazorBindings.WebView.Android?

**Comment by Daddoon** [comment]
This issue is then not related to BlazorMobile.

Otherwise, Microsoft.aspnetcore.components.webassembly is a .NET Standard 2.1 library (check on Nuget).
This mean that if you are referencing it through a .NET Standard 2.0 project it cannot build.

Upgrade your own conflicting project from .NET Standard 2.0 to 2.1, and i think your build error should be gone.
