### ISSUE TITLE
Azure DevOps Pipeline

### ISSUE THREAD

**Issue by shawndeggans** [Daddoon/BlazorMobile#94]
I'm not sure if this will be helpful to you or anyone else, but I built this for the template generated by dotnet new blazormobile solution to work in Azure DevOps Pipeline. 

[azure-pipelines.txt](https://github.com/Daddoon/BlazorMobile/files/3548085/azure-pipelines.txt)

**Comment by Daddoon** [comment]
Hi Scarber !

Thanks for your contribution!
I think since i have created this repository, you are the first person to post and contribute in "issues", even if the star counter is growing.

I'm not an expert about Azure, as i never used it directly. Is this script mean to be used with the tooling of this repository ? Or is it for automatize a user project APK generation ? If yes when ?

Thanks in advance for your explanation! I don't use build system at the moment for this plugin development, but it's more because i don't have enough time to focus on at the moment.

**Comment by Daddoon** [comment]
As i think about it, do not hesitate to read the section about [Android Build size optimization](https://github.com/Daddoon/BlazorMobile#android-build-size-optimization)

**Comment by shawndeggans** [comment]
This script is meant to work within the DevOps Pipeline for the user project APK generation. Presently, it only builds it to an archive, but I think I will eventually have it picked up and delivered to Genymotion On Demand. Thanks for this great project. I can it has a lot of potential.

**Comment by Daddoon** [comment]
Great !

I will post something for this on the README, and put it as an extra asset of the project.
As i'm on vacation, i will do this in few days.

Thanks for your feedback!
Actually thanks to Microsoft Team, Steve Sanderson and Dan Roth for Blazor too!

Web / Hybrid / Native app with just full C# stack is just a developer dream!

Not the subject here, but just for your info on the next version that i will ship:

- Non-async call (Everything except Task and Task<> with or without async keyword) will be deprecated in the MethodDispatcher helper.
- Writing your own code to call the native side will not be mandatory anymore, you will just have to declare your interface in Blazor side and you are done!

Under the hood, i'm writing an MSBuild task that will generate a proxy class for your ProxyInterface annoted interfaces, and so prevent to write the call to native yourself.

Typically you will just have to inject your service from a Razor component or Razor page and call the method and that's it.

Actually this requirement to call yourself the helper method was because WASM implementation does not support JIT/Emit of code, or even if it seem it's possible in some way, it would not be efficient in the browser executing WASM to generate IL.

With the MSBuild solution, this workaround any runtime problematic solution, as it's at build time.

**Comment by Daddoon** [comment]
This as been added to my upcoming release today, in the README. Thanks for contributing !
